#!/bin/bash

# similar to C++ header guard
if [ -n "$__UTIL_GUARD__" ]; then return; fi
__UTIL_GUARD__=1

function randomstring() {
    echo $(date | md5sum | cut -d ' ' -f 1);
}

# readlink in mac does not allow me to do follow, so implement it as a function instead
# reference: http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
function followlink() {
    if [ -z "$1" ]; then
        echo ""
        return 0
    fi
    TARGET_FILE=$1
    cd $(dirname $TARGET_FILE)
    TARGET_FILE=$(basename $TARGET_FILE)
    while [ -L "${TARGET_FILE}" ];
    do
        TARGET_FILE=$(readlink ${TARGET_FILE})
        cd $(dirname $TARGET_FILE)
        TARGET_FILE=$(basename ${TARGET_FILE})
    done

    echo $(pwd -P)/$(basename ${TARGET_FILE})
    return 0
}

function set_title {
    echo -ne "\033]0;"$*"\007"
}

