#!/bin/bash
# locale
LC_CTYPE="en_US.UTF-8"
# export TERM=xterm-256color

# various ls alias based on which type of system we are in
OS_TYPE="$(uname)"

if [ "${OS_TYPE}" == "Darwin" ]; then
    alias l='ls -Glh'
    alias ll='ls -Glh'
    alias wget="curl -O"
elif [ "${OS_TYPE}" == "Linux" ]; then
    alias ll='ls -lh --color'
    alias l='ls -lh --color'
fi

# http://superuser.com/questions/124845/can-you-disable-the-ctrl-s-xoff-keystroke-in-putty
stty -ixon

bind 'set bind-tty-special-chars off'

#################### Vim and Nvim ####################
# set 'v' alias based on if nvim is present
if [ -n "$(which nvim)" ]; then
    alias v="nvim"
    alias vr="nvim -R"
    export EDITOR='nvim'
else
    alias v="vim"
    alias vr="vim -R"
    export EDITOR='vim'
fi
#################### Vim and Nvim ####################

#################### GIT and TIG ####################
# set g and t as git and tig if present
if [ -n "$(which git)" ]; then
    alias g="git"
else
    alias g="echo git is not installed"
fi

if [ -n "$(which tig)" ]; then
    alias t='tig'
else
    alias t="echo tig is not installed"
fi
#################### GIT and TIG ####################

#################### Python ####################
if [ -n "$(which python)" ]; then
    alias p="python"
else
    alias p="echo python is not installed"
fi
#################### Python ####################

#################### Apparix ####################
if [ -n "$(which apparix)" ]; then
    alias a="apparix"
else
    alias a="echo apparix is not installed"
fi
#################### Apparix ####################

# disable rm
alias rm='echo "do not use rm, use trash-put(trash) instead "; false'

# various cd
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."
alias .......="cd ../../../../../.."

# flake8
alias f8="flake8"
