#!/bin/bash

function _kubectl() {
    REPLACE=$(kube-parse-args.py $*)
    kubectl ${REPLACE}
}

if [ -n "$(which kubectl)" ]; then
    if [ -n "$(which kube-parse-args.py)" ]; then
        alias k=_kubectl
    else
        alias k=kubectl
    fi
fi
