#!/bin/bash
# PS

################# GIT ###################
parse_git_branch ()
{
    echo -e $(git branch 2>/dev/null| sed -n '/^\*/s/^\* //p')
}

branch_color ()
{
    color=""
    if git diff --quiet 2>/dev/null >&2
    then
        if git diff --cached --quiet 2> /dev/null >&2
        then
            color="$(tput setab 28)$(tput setaf 255)"
        else
            color="$(tput setab 94)$(tput setaf 255)"
        fi
    else
        color="$(tput setab 88)$(tput setaf 255)"
    fi
    echo -ne $color
}
get_git ()
{
    echo '$(_get_git)'
}

# stole from https://github.com/riobard/bash-powerline/blob/master/bash-powerline.sh
readonly GIT_NEED_PUSH_SYMBOL='⇡'
readonly GIT_NEED_PULL_SYMBOL='⇣'
git_ahead_behind() {
    local marks=""
    local stat="$(git status --porcelain --branch | grep '^##' | grep -o '\[.\+\]$')"
    local aheadN="$(echo $stat | grep -o 'ahead [[:digit:]]\+' | grep -o '[[:digit:]]\+')"
    local behindN="$(echo $stat | grep -o 'behind [[:digit:]]\+' | grep -o '[[:digit:]]\+')"
    [ -n "$aheadN" ] && marks+=" $GIT_NEED_PUSH_SYMBOL$aheadN"
    [ -n "$behindN" ] && marks+=" $GIT_NEED_PULL_SYMBOL$behindN"
    [ -z "$marks" ] && marks+=" "
    echo -n "${marks}"
}
_get_git()
{
    if git rev-parse --git-dir >/dev/null 2>&1; then
        echo "$(branch_color) ⑂ $(parse_git_branch)$(git_ahead_behind) $(tput sgr0)"
    else
        return 0
    fi
}

#########################################

################# Host ##################
get_hostname ()
{
    if [ -e ~/.dotfiles/hostname ]; then
        echo "$(tput setab 25)$(tput setaf 15) $(cat ~/.dotfiles/hostname) $(tput sgr0)"
    else
        echo ""
    fi
}
get_user_host ()
{
    echo "$(tput setab 243)$(tput setaf 15) \u $(tput sgr0)$(get_hostname)"
}

#########################################

################ bound ##################
bound_left ()
{
    echo "$(tput setab 236) $(tput setab 238) $(tput setab 240) $(tput setab 242) $(tput setab 244) $(tput setab 246) $(tput setab 248) $(tput setab 250) $(tput setab 252) $(tput sgr0)"
}
bound_right ()
{
    echo "$(tput setab 252) $(tput setab 250) $(tput setab 248) $(tput setab 246) $(tput setab 244) $(tput setab 242) $(tput setab 240) $(tput setab 238) $(tput setab 236) $(tput sgr0)"
}
#########################################

############### working dir #############
get_working_dir ()
{
    echo "$(tput setab 90)$(tput setaf 15) \w $(tput sgr0)"
}
#########################################

PS1="$(bound_left)$(get_working_dir)$(get_user_host)$(get_git)$(bound_right)\n> "
PS2="> "

