#!/usr/env bash

_load_pyenv() {
    if [ -z "$1" ]; then
        if [ -e "venv" ]; then
            DIR='venv'
        elif [ -e "venv3" ]; then
            DIR='venv3'
        else
            echo "No virtualenv"
            return
        fi
    else
        DIR=$1
    fi

    source $DIR/bin/activate
}

_pyenv ()
{
    if [ "$1" == "-d" ]; then
        return _force_pyenv $*
    fi
    ENV=$1

    if [ -z "$1" ]; then
        ENV='3'
    elif [ "$ENV" == "3" -o "$ENV" == "2" ]; then
        ENV=$ENV
    else
        echo "Unknown Environment (valid values are '2' or '3')"
        return 1
    fi

    if [ "$ENV" == "2" ]; then
        DIR="venv"
        ODIR="venv3"
        PYRUNTIME="python"
    else
        DIR="venv3"
        ODIR="venv"
        PYRUNTIME="python3"
    fi
    if [ ! -e "$DIR" ]; then
        if [ -e "$ODIR" -a -z "$1" ]; then
            DIR=$ODIR
        else
            virtualenv -p $PYRUNTIME $DIR
        fi
    fi

    _load_pyenv $DIR
}

alias pyenv='_pyenv'

_venv34 ()
{
    pyvenv-3.4 --without-pip $1 && source $1/bin/activate && curl https://bootstrap.pypa.io/get-pip.py | python && deactivate && source $1/bin/activate
}

alias virtualenv3='_venv34'
export PYTHONSTARTUP="$HOME/.pythonrc"

_pyinterpreter ()
{
    if [ -e 'venv3' ]; then
        ipython3
    elif [ -e 'venv' ]; then
        ipython
    else
        ipython3
    fi
}

alias pyinterp='_pyinterpreter'
